[package]
name = "kafka-client"
version.workspace = true
edition.workspace = true

[dependencies]
rdkafka.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
tokio.workspace = true

